#!/bin/sh

# Mount core file systems
mount -t proc  proc  /proc
mount -t sysfs sysfs /sys

# Populate /dev from sysfs
mdev -s

# Provide compatibility for tools expecting mtab
ln -s /proc/mounts /etc/mtab

# Mount floppy root & bind /home to persistent storage
mkdir -p /mnt/floppy /mnt/cd /home
mount -t msdos -o rw /dev/fd0 /mnt/floppy
mkdir -p /mnt/floppy/data
mount --bind /mnt/floppy/data /home

[ -r /etc/hostname ] && hostname "$(cat /etc/hostname)"

# Show welcome banner
clear
printf "\x1b[37;44m"
cat banners/welcome
printf "\x1b[0m"
printf "\n\n"

# Show welcome tip
printf "Welcome, please check out \033[32mshorkhelp\033[0m to get started with @NAME@!"
printf "\n\n"

cd /home
/bin/sh
